### ISSUE TITLE
dummyRes file not exist

### ISSUE THREAD

**Issue by arslanahmedawan** [sarslancs/wbc_segmentation#1]
There is an error in **circle_fit.m** file at **line 50**
**Reason:** dummyRes file not exist.

Error using load
Unable to read file 'dummyRes'. No such file or directory.
Error in circle_fit (line 50)
    cMap = load('dummyRes');

**Comment by sarslancs** [comment]
You get this error as you haven't (successfully) compiled the source code provided in the `circleFitNative` folder. `circle_fit`, in particular line 45 relies on this external library. Please follow the following instructions to compile the C files before attempting to run the program. It should work on Windows and Unix envs.

> 1. Open a terminal
> 2. cd into <directory you extracted Matlab source>/circleFitNative
> 3. run gcc *.c -o circleFit_exe -lm
> Note: If you change the name of the exe file above, do not forget to apply the
> same change to your repo (i.e. line 45)

Hope this helps.

**Comment by arslanahmedawan** [comment]
Not Working.
**Error:** Stopped Working Accidentally.

**Comment by sarslancs** [comment]
The above solution works on my machine, which runs Ubuntu, as well as on a Mac. It used to work for Windows, the platform I have implemented this on. I am afraid I do not have a solution for the latest error and I do not think it is related to the original issue anymore. I am closing this issue now, but feel free to open a new one if you think the error is due to a bug in the code.
